(function(){
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
SLY.Economy={
 departmentPower:d=>SLY.Employees.departmentPower(d),
 effectiveProduct(id){const s=SLY.State.get(),p=s.products[id],b=SLY.Tech.productBonus(id,p);return{quality:clamp(p.quality+b.quality),demand:clamp(p.demand+b.demand),cost:Math.max(1,p.cost*(1+b.costPct/100)),capacity:b.capacity,stability:b.stability}},
 incomePerHour(){const s=SLY.State.get();const finance=this.departmentPower('finance');let base=220+s.departments.finance.level*180;const market=s.market||{};base*=.72+(market.confidence||60)/220;return Math.max(0,Math.round(base*(1+finance/4200)))},
 startSale(id){const s=SLY.State.get(),p=s.products[id];if(!p?.completed||p.activeSale)return{ok:false,reason:'Produit non prêt ou vente déjà active.'};const e=this.effectiveProduct(id),reviews=p.reviews.length?p.reviews.reduce((a,r)=>a+r.stars,0)/p.reviews.length:3.8,marketing=this.departmentPower('marketing'),market=s.market||{};const sector=market.sectors?.[p.sector]??65;const priceRatio=p.price/Math.max(1,e.cost),pricePenalty=Math.max(0,(priceRatio-1.9)*18);const demand=clamp(e.demand+(s.reputation-70)*.28+marketing/36+(e.quality-70)*.25+(reviews-3)*4-pricePenalty+(sector-65)*.35-(market.volatility||18)*.12,5,100);const duration=180000;const cap=Math.round((28+demand*2.05)*(1+e.capacity/100)*(1+s.departments.production.level*.035));p.activeSale={started:Date.now(),duration,units:0,revenue:0,paid:0,demand,capacity:cap,marketFactor:1};s.xp+=5;SLY.Events.news('Lancement commercial',`${p.name} entre sur le marché · demande ${Math.round(demand)}% · potentiel ${cap} unités.`,'sales');SLY.Audio.play('money');return{ok:true}},
 tick(dt){const s=SLY.State.get(),h=dt/3600000;if(h<=0)return;const hourly=this.incomePerHour(),salary=s.employees.reduce((a,e)=>a+e.salary,0)/24;const baseline=Math.max(-hourly*.8,(hourly-salary)*h);s.money=Math.max(0,s.money+baseline);s.company.value=Math.max(100000,s.company.value+Math.max(0,baseline)*10);s.xp+=Math.max(0,h*3+Math.max(0,baseline)/100000);s.minute+=h*60;while(s.minute>=1440){s.minute-=1440;s.day++;s.stats.daysPlayed++;SLY.Corp.dailyClose()}
 s.fans=Math.max(0,Math.round(s.fans+(s.reputation-68)*.16*h));
 Object.values(s.products).forEach(p=>{if(!p.activeSale)return;const sale=p.activeSale,e=this.effectiveProduct(p.id),elapsed=Date.now()-sale.started,power=Math.max(.45,sale.demand/100)*(0.62+this.departmentPower('marketing')/500)*(sale.marketFactor||1);const newUnits=Math.min(sale.capacity,Math.max(sale.units,Math.floor(elapsed/1000*power)));const unitMargin=Math.max(0,p.price-e.cost);sale.units=newUnits;const targetRevenue=sale.units*unitMargin;const delta=Math.max(0,targetRevenue-sale.paid);if(delta>0){s.money+=delta;s.company.value+=delta*.1;s.stats.revenue+=delta;s.stats.grossProfit+=delta;sale.paid+=delta}sale.revenue=targetRevenue;if(elapsed>=sale.duration)SLY.Production.finishSale(p.id)});
 if(typeof SLY.Investors!=='undefined')SLY.Investors.tick();
 },
 reprice(id,price){const s=SLY.State.get(),p=s.products[id];if(!p||!Number.isFinite(price))return false;const min=Math.max(1,Math.round(p.cost*.75)),max=Math.round(p.cost*4.5);if(price<min||price>max)return false;p.price=Math.round(price);SLY.Events.news('Prix ajusté',`${p.name} est désormais affiché à ${p.price.toLocaleString('fr-FR')} $.`,'sales');return true}
};
})();
