(function(){
const KEY='SLYWORD_ULTIMATE_V7';
const LEGACY_KEYS=['SLYWORD_ULTIMATE_V6','SLYWORD_ULTIMATE_V5','SLYWORD_ULTIMATE_V2','SLYWORD_ULTIMATE_V1'];
const competitors={
 TECHNOVA:{capital:98400000,reputation:87,security:72,level:16,technology:8,sector:'IA & cloud',style:'aggressive',focus:'innovation',aggression:1.25},
 CYBERDYNE:{capital:85300000,reputation:85,security:78,level:15,technology:9,sector:'Cyberdéfense',style:'defensive',focus:'security',aggression:.65},
 INFINITY:{capital:76200000,reputation:82,security:68,level:14,technology:7,sector:'Fintech',style:'financial',focus:'finance',aggression:.8},
 OMNITECH:{capital:64800000,reputation:78,security:61,level:13,technology:6,sector:'Robotique',style:'industrial',focus:'production',aggression:.9},
 NEXORA:{capital:58300000,reputation:74,security:58,level:12,technology:6,sector:'Semi-conducteurs',style:'tech',focus:'technology',aggression:1},
 QUANTUM:{capital:52100000,reputation:72,security:55,level:11,technology:5,sector:'Mobilité',style:'mobility',focus:'mobility',aggression:.85}
};
const product=(id,name,asset,price,cost,quality,demand,stages,tech,sector)=>({id,name,asset,price,cost,quality,demand,stage:0,stages,costs:stages.map((_,i)=>Math.round(12000+i*7000+cost/12)),tech,sector,units:0,revenue:0,reviews:[],activeSale:null,completed:false,marketing:0});
const products=()=>({
 phone:product('phone','S-PHONE 1','assets/products/phone.svg',699,360,70,70,['Conception','Écran AMOLED','Processeur SLY Chip','Caméra IA','Batterie haute capacité','SLY OS'],[null,'oled','slychip','aicam','battery','slyos'],'mobile'),
 drone:product('drone','SKY DRONE X1','assets/products/drone.svg',1290,620,55,54,['Conception','Propulsion','Vision IA','Navigation','Batterie','SkyOS'],[null,'propulsion','vision','navigation','battery','slyos'],'mobility'),
 laptop:product('laptop','SLYBOOK PRO','assets/products/laptop.svg',1499,760,52,46,['Conception','Châssis','OLED','SLY Chip','IA embarquée','SLY OS'],[null,'materials','oled','slychip','advancedai','slyos'],'computing'),
 car:product('car','S-MOTION','assets/products/car.svg',42000,25500,45,32,['Conception','Batterie','Autonomie','IA conduite','Châssis','Production'],[null,'battery','range','advancedai','materials','robotics'],'mobility'),
 robot:product('robot','S-BOT 1','assets/products/robot.svg',8900,4100,42,25,['Conception','Servomoteurs','Vision','IA','Sécurité','SLY OS'],[null,'robotics','vision','advancedai','security','slyos'],'robotics')
});
const initial=()=>({version:7,day:1,minute:480,money:325000,techPoints:8450,fans:45780,reputation:92,level:1,xp:0,
 company:{name:'SLYWORD CORP.',value:12575000,influence:35,stability:92,sharePrice:184},competitors:JSON.parse(JSON.stringify(competitors)),products:products(),
 technologies:{oled:{name:'Écran OLED',cost:900,req:null,effect:'Qualité +7',bonus:{quality:7}},slychip:{name:'SLY CHIP',cost:1500,req:'oled',effect:'Qualité +9 · coût -4%',bonus:{quality:9,cost:-4}},aicam:{name:'Caméra IA',cost:2000,req:'slychip',effect:'Qualité +8 · demande +4%',bonus:{quality:8,demand:4}},battery:{name:'Batterie avancée',cost:1200,req:null,effect:'Capacité de vente +8%',bonus:{saleCapacity:8}},slyos:{name:'SLY OS',cost:1800,req:'aicam',effect:'Qualité +6 · demande +6%',bonus:{quality:6,demand:6}},propulsion:{name:'Propulsion X',cost:1400,req:null,effect:'Drone qualité +7',bonus:{quality:7,products:['drone']}},navigation:{name:'Navigation IA',cost:2100,req:'aicam',effect:'Drone demande +9%',bonus:{demand:9,products:['drone']}},materials:{name:'Matériaux de pointe',cost:1200,req:null,effect:'Coût fabrication -10%',bonus:{cost:-10}},advancedai:{name:'IA avancée',cost:2000,req:'slyos',effect:'Qualité +12',bonus:{quality:12}},robotics:{name:'Robotique',cost:2200,req:'materials',effect:'Capacité de vente +12%',bonus:{saleCapacity:12}},vision:{name:'Vision machine',cost:1300,req:null,effect:'Drone/robot qualité +7',bonus:{quality:7,products:['drone','robot']}},range:{name:'Autonomie longue portée',cost:1700,req:'battery',effect:'Mobilité demande +8%',bonus:{demand:8,products:['drone','car']}},security:{name:'Sécurité embarquée',cost:1100,req:null,effect:'Stabilité +4',bonus:{stability:4}}},
 unlockedTech:['oled','battery','materials'],militaryTech:{intel:{name:'Renseignement',cost:600,effect:'+8% espionnage'},surveillance:{name:'Surveillance',cost:900,effect:'+6% contre-détection'},counter:{name:'Contre-espionnage',cost:1200,effect:'+10% sécurité'},advancedops:{name:'Opérations avancées',cost:1800,effect:'+12% sabotage'}},unlockedMilitaryTech:[],
 departments:{production:{name:'Production',level:3,employees:[]},rd:{name:'R&D',level:2,employees:[]},marketing:{name:'Marketing',level:2,employees:[]},finance:{name:'Finance',level:1,employees:[]},security:{name:'Sécurité',level:2,employees:[]},military:{name:'Militaire',level:1,employees:[]}},employees:[],candidates:[],candidateSeq:0,needs:[],news:[{time:'J1 · 08:00',title:'SLYWORD inaugure son centre mondial',body:'Le marché observe le nouvel empire avec attention.',type:'company'}],investors:[],missions:[],reports:[],
 stats:{sales:0,produced:12450,unitsSold:0,revenue:0,grossProfit:0,successfulMissions:0,failedMissions:0,partialMissions:0,acceptedNeeds:0,investments:0,daysPlayed:0},
 market:{demand:68,innovation:52,operations:55,confidence:64,security:58,brand:72,volatility:18,cycle:'expansion',cycleProgress:12,trend:0,sectors:{mobile:74,mobility:61,computing:66,robotics:58}},
 goals:{products:1,sales:500,tech:6,employees:6,missions:1},achievements:[],milestones:[],lastDayReport:1,settings:{music:70,sfx:85,muted:false},lastSave:Date.now()});
let state=initial();
function merge(a,b){if(!b||typeof b!=='object')return a;Object.keys(b).forEach(k=>{if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k]&&typeof a[k]==='object')a[k]=merge(a[k],b[k]);else a[k]=b[k]});return a}
function migrate(raw){const s=merge(initial(),raw||{});s.version=7;s.stats=merge(initial().stats,s.stats||{});s.market=merge(initial().market,s.market||{});s.market.sectors=merge(initial().market.sectors,s.market.sectors||{});s.goals=merge(initial().goals,s.goals||{});s.achievements=s.achievements||[];s.milestones=s.milestones||[];Object.values(s.competitors||{}).forEach(c=>{c.style=c.style||'tech';c.focus=c.focus||'innovation';c.aggression=c.aggression??1});Object.values(s.products||{}).forEach(p=>{p.sector=p.sector||'computing';p.units=Number(p.units||0);p.revenue=Number(p.revenue||0);p.reviews=p.reviews||[]});s.stats.sales=Math.max(Number(s.stats.sales||0),Number(s.stats.unitsSold||0));s.stats.unitsSold=Number(s.stats.unitsSold||s.stats.sales||0);return s}
window.SLY=window.SLY||{};SLY.State={KEY,LEGACY_KEYS,initial,get:()=>state,set:v=>state=v,reset:()=>{state=initial();return state},load(){try{let raw=localStorage.getItem(KEY);for(const k of LEGACY_KEYS){if(!raw)raw=localStorage.getItem(k)}if(raw)state=migrate(JSON.parse(raw))}catch(e){console.warn(e)}return state}};
})();
