(function(){
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const pick=a=>a[Math.floor(Math.random()*a.length)];
SLY.Corp={_last:{},_clock:0,
 ensure(){const s=SLY.State.get();s.market=s.market||SLY.State.initial().market;return s.market},
 snapshot(){const s=SLY.State.get();return{money:s.money,rep:s.reputation,level:s.level,sales:s.stats.sales,tech:s.unlockedTech.length,employees:s.employees.length,needs:s.needs.length,value:s.company.value}},
 dailyClose(){const s=SLY.State.get(),m=this.ensure();m.cycleProgress=(m.cycleProgress||0)+1;if(m.cycleProgress>=6){m.cycleProgress=0;const cycles=['expansion','boom','correction','recovery'];m.cycle=cycles[(cycles.indexOf(m.cycle)+1+cycles.length)%cycles.length];this._last.cycle='';SLY.Events.news('Nouveau cycle économique','Le marché entre en phase '+m.cycle+'. Les secteurs réagissent différemment.','market')}
 const ready=Object.values(s.products).filter(p=>p.completed).length;const avgSales=ready?Object.values(s.products).filter(p=>p.completed).reduce((a,p)=>a+p.demand,0)/ready:40;const cycleBias={expansion:4,boom:10,correction:-9,recovery:1}[m.cycle]||0;m.trend=clamp((avgSales-55)*.35+cycleBias,-20,20);Object.keys(m.sectors).forEach(k=>{const sectorBias={mobile: m.cycle==='boom'?4:0,mobility:m.cycle==='recovery'?5:0,computing:m.cycle==='correction'?-3:2,robotics:m.cycle==='expansion'?3:-1}[k]||0;m.sectors[k]=clamp(m.sectors[k]+(Math.random()*4-2)+sectorBias*.25+m.trend*.05,20,95)});
 if(s.day%2===0&&Math.random()<.7)SLY.Population.spawn();
 if(s.day!==s.lastDayReport){s.lastDayReport=s.day;SLY.Events.news('Clôture quotidienne',`J${s.day} · capital ${Math.round(s.money).toLocaleString('fr-FR')} $ · ${s.stats.sales.toLocaleString('fr-FR')} ventes cumulées.`,'company')}
 this.checkMilestones();
 },
 checkMilestones(){const s=SLY.State.get(),tests=[['first_sale',s.stats.sales>=1,'Premier contrat','Réaliser votre première vente.',12000],['million',s.company.value>=100000000,'Cent millions','Atteindre 100 M$ de valeur d’entreprise.',25000],['three_products',Object.values(s.products).filter(p=>p.completed).length>=3,'Portefeuille majeur','Terminer trois produits.',40000],['tech_master',s.unlockedTech.length>=9,'Laboratoire avancé','Débloquer neuf technologies.',50000],['global_brand',s.reputation>=98&&s.fans>=100000,'Marque mondiale','Atteindre 98% de réputation et 100k fans.',75000],['market_leader',Object.values(s.competitors).every(c=>s.company.value>=c.capital),'Leader mondial','Dépasser tous les concurrents en valeur.',150000]];tests.forEach(([id,ok,title,body,reward])=>{if(ok&&!s.achievements.includes(id)){s.achievements.push(id);s.money+=reward;s.xp+=20;SLY.Events.news('OBJECTIF DÉBLOQUÉ',`${title} · récompense ${reward.toLocaleString('fr-FR')} $.`,'achievement');SLY.Audio.play('success')}})},
 tick(dt){const s=SLY.State.get(),m=this.ensure(),h=dt/3600000;if(h<=0)return;const prod=SLY.Employees.departmentPower('production'),rd=SLY.Employees.departmentPower('rd'),marketing=SLY.Employees.departmentPower('marketing'),finance=SLY.Employees.departmentPower('finance'),security=SLY.Employees.departmentPower('security'),mil=SLY.Employees.departmentPower('military');const ready=Object.values(s.products).filter(p=>p.completed).length;const quality=avg(Object.values(s.products).map(p=>p.quality));
 m.operations=clamp(36+prod/13+finance/38+ready*3);m.innovation=clamp(34+rd/11+s.unlockedTech.length*2.8);m.brand=clamp(42+s.reputation*.44+marketing/18+s.fans/140000);m.security=clamp(32+security/14+mil/22+s.unlockedMilitaryTech.length*3);m.confidence=clamp((s.reputation+s.company.stability)/2+finance/48+(s.company.value>150000000?4:0));const pressure=clamp(s.needs.length*6+(70-s.reputation)*.45,0,35);m.volatility=clamp(12+(100-s.company.stability)*.42+pressure);m.demand=clamp(46+quality*.4+m.brand*.12+m.operations*.08-m.volatility*.17+(m.trend||0));
 Object.values(s.products).forEach(p=>{const e=SLY.Economy.effectiveProduct(p.id),sector=m.sectors[p.sector]||65;const target=clamp(p.demand+(m.demand-p.demand)*.014+(sector-65)*.01+(e.quality-quality)*.025+marketing/1300-(m.volatility-20)*.008);p.demand=target;if(p.activeSale)p.activeSale.marketFactor=1+m.brand/700+m.confidence/1200-m.volatility/1350});
 s.company.influence=clamp(28+s.level*1.9+m.brand*.34+s.stats.sales/8000);s.company.stability=clamp(56+m.security*.24+m.confidence*.2-s.needs.length*1.8);
 if(s.needs.length>=3&&Math.random()<.025*h)s.reputation=clamp(s.reputation-.18);
 SLY.Population.tick();
 Object.entries(s.competitors).forEach(([name,c])=>{const cycle={expansion:1.02,boom:1.08,correction:.9,recovery:.98}[m.cycle]||1;const focusBoost={innovation:1.04,security:1.02,finance:1.035,production:1.03,technology:1.035,mobility:1.03}[c.focus]||1;const growthPerHour={aggressive:.0018,defensive:.0012,financial:.0015,industrial:.0014,tech:.00155,mobility:.0013}[c.style]||.0013;const efficiency=(1+(c.level/1000))*(1+(c.technology/600))*cycle*focusBoost;c.capital=Math.max(0,c.capital*(1+growthPerHour*h*efficiency));if(Math.random()<.05*h){const dir=Math.random()<.58?1:-1;c.reputation=clamp(c.reputation+dir*(.4+c.aggression*.2));}
 if(c.style==='defensive')c.security=clamp(c.security+(.06+(security>75?.03:0))*h);if(c.style==='aggressive'&&Math.random()<.035*h*c.aggression){s.reputation=clamp(s.reputation-.3);s.company.stability=clamp(s.company.stability-.25);this._last[name]=Date.now();SLY.Events.news('Offensive concurrentielle',`${name} lance une campagne agressive contre SLYWORD.`,'market')}
 if(c.style==='financial'&&Math.random()<.025*h)c.capital+=Math.max(50000,s.company.value*.0004);if(c.style==='tech'&&Math.random()<.02*h)c.technology=Math.min(30,c.technology+1);if(c.style==='industrial'&&Math.random()<.025*h)c.capital+=prod*18*h;if(c.style==='mobility'&&Math.random()<.02*h)c.reputation=clamp(c.reputation+1);if(s.company.value>c.capital*1.12&&Math.random()<.015*h){c.reputation=clamp(c.reputation+1);c.security=clamp(c.security+1);SLY.Events.news('Rattrapage concurrent',`${name} accélère ses investissements pour rattraper SLYWORD.`,'market')}});
 const oldLevel=s.level;if(s.xp>=100){const levels=Math.floor(s.xp/100);s.level+=levels;s.xp-=levels*100;s.reputation=clamp(s.reputation+levels*.6);s.company.value+=levels*50000;SLY.Events.news('Niveau supérieur','SLYWORD atteint le niveau '+s.level+'.','level');SLY.Audio.play('success')}if(s.level!==oldLevel)SLY.Corp.checkMilestones();this._clock+=dt;this.checkMilestones();
 },action(kind,payload={}){SLY.Audio.play(kind);if(kind==='money')SLY.Anim.float('+'+(payload.amount||0).toLocaleString('fr-FR')+' $')}};
})();
